server {
    listen 80;

    # JokeAPI
    location /api/joke {
        proxy_pass https://v2.jokeapi.dev/joke/Programming?type=single;
        proxy_ssl_server_name on;
    }

    # RandomFox
    location /api/fox {
        proxy_pass https://randomfox.ca/floof/;
        proxy_ssl_server_name on;
    }

}